/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-06-01 12:51:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DecisionTreeIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script src=\"/jquery-2.1.4.js\"></script>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Details</title>\n");
      out.write("<h1>Recommendation Decision Tree</h1>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      out.print( "Fill in your level and interests" );
      out.write("\n");
      out.write("\t<hr />\n");
      out.write("\t<label style=padding-left:1px>Level</label>\n");
      out.write("\t<label style=padding-left:50px>Interest Tag 1</label>\n");
      out.write("\t<label style=padding-left:50px>Interest Tag 2</label>\n");
      out.write("\t<label style=padding-left:50px>Interest Tag 3</label>\n");
      out.write("\t\n");
      out.write("\t<form name=\"userform\" method=\"post\" action=\"submitLevel\">\n");
      out.write("\t\n");
      out.write("\t<select property=\"level\" name=\"level\">\n");
      out.write("\t<option value=\"0\">Select Level</option>\n");
      out.write("\t<option value=\"1\">Beginner</option>\n");
      out.write("\t<option value=\"2\">Advanced</option>\n");
      out.write("\t</select>\n");
      out.write("\t\n");
      out.write("\t<select property=\"Tag1\" name=\"tag1\">\n");
      out.write("\t<option value=\"0\">Select Tag1</option>\n");
      out.write("\t<option value=\"1\">HTML</option>\n");
      out.write("\t<option value=\"2\">Javascript</option>\n");
      out.write("\t<option value=\"3\">JQuery</option>\n");
      out.write("\t<option value=\"4\">CSS</option>\n");
      out.write("\t<option value=\"5\">Responsive</option>\n");
      out.write("\t<option value=\"6\">Hadoop</option>\n");
      out.write("\t<option value=\"7\">Spark</option>\n");
      out.write("\t<option value=\"8\">R</option>\n");
      out.write("\t<option value=\"9\">Machine Learning</option>\n");
      out.write("\t<option value=\"10\">Android</option>\n");
      out.write("\t<option value=\"11\">Mobile</option>\n");
      out.write("\t<option value=\"12\">Google Services</option>\n");
      out.write("\t<option value=\"13\">Physics</option>\n");
      out.write("\t<option value=\"14\">Algebra</option>\n");
      out.write("\t<option value=\"15\">Psychology</option>\n");
      out.write("\t<option value=\"16\">Chemistry</option>\n");
      out.write("\t</select>\n");
      out.write("\t\n");
      out.write("\t<select property=\"Tag2\" name=\"tag2\">\n");
      out.write("\t<option value=\"0\">Select Tag2</option>\n");
      out.write("\t<option value=\"1\">HTML</option>\n");
      out.write("\t<option value=\"2\">Javascript</option>\n");
      out.write("\t<option value=\"3\">JQuery</option>\n");
      out.write("\t<option value=\"4\">CSS</option>\n");
      out.write("\t<option value=\"5\">Responsive</option>\n");
      out.write("\t<option value=\"6\">Hadoop</option>\n");
      out.write("\t<option value=\"7\">Spark</option>\n");
      out.write("\t<option value=\"8\">R</option>\n");
      out.write("\t<option value=\"9\">Machine Learning</option>\n");
      out.write("\t<option value=\"10\">Android</option>\n");
      out.write("\t<option value=\"11\">Mobile</option>\n");
      out.write("\t<option value=\"12\">Google Services</option>\n");
      out.write("\t<option value=\"13\">Physics</option>\n");
      out.write("\t<option value=\"14\">Algebra</option>\n");
      out.write("\t<option value=\"15\">Psychology</option>\n");
      out.write("\t<option value=\"16\">Chemistry</option>\n");
      out.write("\t</select>\n");
      out.write("\t\n");
      out.write("\t<select property=\"Tag3\" name=\"tag3\">\n");
      out.write("\t<option value=\"0\">Select Tag3</option>\n");
      out.write("\t<option value=\"1\">HTML</option>\n");
      out.write("\t<option value=\"2\">Javascript</option>\n");
      out.write("\t<option value=\"3\">JQuery</option>\n");
      out.write("\t<option value=\"4\">CSS</option>\n");
      out.write("\t<option value=\"5\">Responsive</option>\n");
      out.write("\t<option value=\"6\">Hadoop</option>\n");
      out.write("\t<option value=\"7\">Spark</option>\n");
      out.write("\t<option value=\"8\">R</option>\n");
      out.write("\t<option value=\"9\">Machine Learning</option>\n");
      out.write("\t<option value=\"10\">Android</option>\n");
      out.write("\t<option value=\"11\">Mobile</option>\n");
      out.write("\t<option value=\"12\">Google Services</option>\n");
      out.write("\t<option value=\"13\">Physics</option>\n");
      out.write("\t<option value=\"14\">Algebra</option>\n");
      out.write("\t<option value=\"15\">Psychology</option>\n");
      out.write("\t<option value=\"16\">Chemistry</option>\n");
      out.write("\t</select>\n");
      out.write("      \n");
      out.write("    <input id=\"Submit\" type=\"submit\" value=\"Submit\" /><br />\n");
      out.write("    <label id=\"Output\"></label>\n");
      out.write("    </form>\n");
      out.write("    <p>\n");
      out.write("    \n");
      out.write("    </p>\n");
      out.write("      <script>\n");
      out.write("      $(document).ready(function(){\n");
      out.write("    \t  console.log(\"Ready\");\n");
      out.write("    \t  var givendata = \"\";\n");
      out.write("    \t $('#Submit').click(function(){\n");
      out.write("    \t\t \n");
      out.write("    \t\t var givendata = \"1 1:\"+$('#level').val() + \" \" +\"2:\"+ $('#tag1').val() + \" \" +\"3:\"+ $('#tag2').val() + \" \" +\"4:\"+ $('#tag3').val();\n");
      out.write("    \t\t console.log(givendata);\n");
      out.write("    \t\t var result = request.getAttribute(\"responseText\");\n");
      out.write("    \t\t $(\"#Output\").text(result);\n");
      out.write("    \t }) \n");
      out.write("      });\n");
      out.write("      </script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
