/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-06-11 17:09:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class IndexHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\n");
      out.write("\t\t<style>\n");
      out.write("\t\t\tdiv.heading {\n");
      out.write("\t\t\t\tbackground-color:orange;\n");
      out.write("\t\t\t\tcolor:white;\n");
      out.write("\t\t\t\tmargin:20px;\n");
      out.write("\t\t\t\tpadding:20px;\n");
      out.write("\t\t\t\tfont-size: 20;\n");
      out.write("\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tinput{\n");
      out.write("\t\t\t\tmargin-top:-125px;\n");
      out.write("\t\t\t\tmargin-left:1070px;\n");
      out.write("\t\t\t\tbackground-color:orange;\n");
      out.write("\t\t\t\tcolor:white;\n");
      out.write("\t\t\t\twidth:100px;\n");
      out.write("\t\t\t\theight: 40px;\n");
      out.write("\t\t\t\tfont-weight:bolder;\n");
      out.write("\t\t\t\tfont-size:large;\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\th1 {\n");
      out.write("\t\t\t\ttext-align: center\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tdiv.even{\n");
      out.write("\t\t\t\tbackground-color:orange;\n");
      out.write("\t\t\t\tcolor:white;\n");
      out.write("\t\t\t\tmargin:20px;\n");
      out.write("\t\t\t\tpadding:20px;\t\n");
      out.write("\t\t\t\twidth:70%;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tdiv.odd{\n");
      out.write("\t\t\t\tbackground-color:orange;\n");
      out.write("\t\t\t\tcolor:white;\n");
      out.write("\t\t\t\tmargin:20px;\n");
      out.write("\t\t\t\tpadding:20px;\n");
      out.write("\t\t\t\twidth:70%;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</style>\n");
      out.write("\t</head>\n");
      out.write("\n");
      out.write("\t<body>\n");
      out.write("\t\n");
      out.write("\t\t<div class=\"heading\">\n");
      out.write("\t\t\t<h1>Personalized Movie Recommendation System</h1>\n");
      out.write("\t\t</div>\n");
      out.write("\t<form name=\"trendingForm\" method=\"post\" action=\"welcomeMain\">\n");
      out.write("\t\t<div class=\"even\">\n");
      out.write("\t\t\t<h2>What's New</h2>\n");
      out.write("\n");
      out.write("\t\t\t<p>See what's trending into the world of movies right now</p>\n");
      out.write("\n");
      out.write("\t\t\t<p>Get recommendations based upon the most trending things in ur favourite movie destination</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<input id=\"SubmitTrending\" type=\"submit\" value=\"Submit\" /><br />\n");
      out.write("\n");
      out.write("    </form>\n");
      out.write("    \n");
      out.write("    <form name=\"CollaborativeForm\" method=\"post\" action=\"ItemRecommenderIndex.jsp\">\n");
      out.write("\t\t \n");
      out.write("\t\t<div class=\"odd\">\n");
      out.write("\t\t\t<h2>What my friends are watching</h2>\n");
      out.write("\n");
      out.write("\t\t\t<p>See what ur friends watching right now</p>\n");
      out.write("\n");
      out.write("\t\t\t<p>Get recommendations based upon the most trending things in ur favourite movie destination</p>\n");
      out.write("\t\t</div> \n");
      out.write("\t\t<input id=\"SubmitCollaborative\" type=\"submit\" value=\"Submit\" /><br />\n");
      out.write("\n");
      out.write("    </form>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("<form name=\"DecisionTreeForm\" method=\"post\" action=\"MovieDecisionTreeIndex.jsp\">\n");
      out.write("<div class=\"even\">\n");
      out.write("\t\t\t<h2>Show me according to my interest</h2>\n");
      out.write("\n");
      out.write("\t\t\t<p>your very personal choice of movies</p>\n");
      out.write("\n");
      out.write("\t\t\t<p>Get recommendations based upon your movie history</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<input id=\"SubmitDecisionTree\"  type=\"submit\" value=\"Submit\" /><br />\n");
      out.write("\n");
      out.write("    </form>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <form name=\"StringMatchBasedForm\" method=\"post\" action=\"JaccardRecommendationIndex.jsp\">\n");
      out.write("<div class=\"odd\">\n");
      out.write("\t\t\t<h2>I have versatile interests</h2>\n");
      out.write("\n");
      out.write("\t\t\t<p>Show me something based upon my favorite genres</p>\n");
      out.write("\n");
      out.write("\t\t\t<p>Get recommendations based upon our Jaccard index</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<input id=\"SubmitJaccardString\"  type=\"submit\" value=\"Submit\" /><br />\n");
      out.write("\n");
      out.write("    </form>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t<form name=\"RatingForm\" method=\"post\" action=\"RatingAuthTest.jsp\">\n");
      out.write("\t\t \n");
      out.write("\t\t<div class=\"even\">\n");
      out.write("\t\t\t<h2>Submit My Ratings</h2>\n");
      out.write("\n");
      out.write("\t\t\t<p>Provide your ratings and reviews to the movies you watched</p>\n");
      out.write("\n");
      out.write("\t\t\t<p>We appreciate your effort to provide ratings and reviews and for making our system better</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<input id=\"SubmitRating\"  type=\"submit\" value=\"Submit\" /><br />\n");
      out.write("\n");
      out.write("    </form>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <form name=\"ReviewForm\" method=\"post\" action=\"ReviewToRatingIndex.jsp\">\n");
      out.write("\t\t \n");
      out.write("\t\t<div class=\"odd\">\n");
      out.write("\t\t\t<h2>Share My Reviews</h2>\n");
      out.write("\n");
      out.write("\t\t\t<p>Provide your reviews to the movies you watched</p>\n");
      out.write("\n");
      out.write("\t\t\t<p>We are happy to get short and sweet textual reviews.</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<input id=\"SubmitReview\"  type=\"submit\" value=\"Submit\" /><br />\n");
      out.write("\n");
      out.write("    </form>\n");
      out.write("\t\t <script type=\"text/javascript\">\n");
      out.write("\t\t \n");
      out.write("\t\t </script>\n");
      out.write("\t\t    \n");
      out.write("\t</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
